achievementData = {
	cardPath = "images/system/banner",
	iconPath = "images/system/icon",
	keyedAchievements = {"stage1", "stage2", "stage3", "stage4", "stage5", "stage6", "stage7", "champ", "rockon", "flawless", "speedy", "sselwalf", "ydeeps", "rockandrow", "speedrun", "pumpkineater"},
	achievements = {
		{
			id = "stage1",
			name = "Short Circuit",
			description = "Complete Stage 1",
			isSecret = false,
			scoreValue = 1,
		},
		{
			id = "stage2",
			name = "Surf Sanctuary",
			description = "Complete Stage 2",
			isSecret = false,
			scoreValue = 1,
		},
		{
			id = "stage3",
			name = "Paddle Beach",
			description = "Complete Stage 3",
			isSecret = false,
			scoreValue = 1,
		},
		{
			id = "stage4",
			name = "Lake Labyrinthus",
			description = "Complete Stage 4",
			isSecret = false,
			scoreValue = 1,
		},
		{
			id = "stage5",
			name = "Roguebot Jungle",
			description = "Complete Stage 5",
			isSecret = false,
			scoreValue = 1,
		},
		{
			id = "stage6",
			name = "Cavern Canal",
			description = "Complete Stage 6",
			isSecret = false,
			scoreValue = 1,
		},
		{
			id = "stage7",
			name = "Robo-X Factory",
			description = "Complete Stage 7",
			isSecret = false,
			scoreValue = 1,
		},
		{
			id = "champ",
			name = "Fish Bowl Champ",
			description = "Complete Circuit 4 of Story Mode",
			isSecret = true,
			scoreValue = 0,
		},
		{
			id = "rockon",
			name = "Rock On",
			description = "Best the Robo-Shark without crashing",
			isSecret = false,
			scoreValue = 1,
		},
		{
			id = "flawless",
			name = "Flawless!",
			description = "Obtain all Flawless medals in Time Trials",
			isSecret = false,
			progressMax = 7,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "speedy",
			name = "Speedy!",
			description = "Obtain all Speedy medals in Time Trials",
			isSecret = false,
			progressMax = 7,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "sselwalf",
			name = "Sselwalf!",
			description = "Obtain all Flawless medals in Time Trials (Mirror Mode)",
			isSecret = false,
			progressMax = 7,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "ydeeps",
			name = "Ydeeps!",
			description = "Obtain all Speedy medals in Time Trials (Mirror Mode)",
			isSecret = false,
			progressMax = 7,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "rockandrow",
			name = "Rock and Row All Night",
			description = "Obtain a score of 50+ on Robo-Shark+",
			isSecret = true,
			scoreValue = 0,
		},
		{
			id = "speedrun",
			name = "Parallel Universes",
			description = "Complete a Speedrun",
			isSecret = true,
			scoreValue = 0,
		},
		{
			id = "pumpkineater",
			name = "Pumpkin Eater",
			description = "Find and use a cheat code",
			isSecret = true,
			scoreValue = 0,
		},
	}
}